insert into real_estate.voivodeship(name) values ('dolnośląskie'), ('kujawsko-pomorskie'), ('lubelskie'), ('lubuskie'),('łódzkie'),('małopolskie'),('mazowieckie'),('opolskie'),('podkarpackie'),('podlaskie'),('pomorskie'),('śląskie'),('świętokrzyskie'),('warmińsko-mazurskie'),('wielkopolskie'),('zachodniopomorskie');
insert into real_estate.city(name) value ('Kraków');
insert into real_estate.district(name) value ('Dąbie');
insert into real_estate.transaction(name) values ('sprzedaż'),('najem'),('dzierżawa');
insert into real_estate.apartments(price,street,area, bathrooms, description, image, lift, parking, rooms, storey, district_id, transaction_id) values (280000,'Bajeczna',50,1,'Mieszkanie położone na Dąbiu, przy ul. Bajecznej',LOAD_FILE('baj1.jpg'),'brak','brak',1,1,1,1);
select *from real_estate.voivodeship;
select *from real_estate.city;
select *from real_estate.district;
select *from real_estate.apartments;
select *from real_estate.transaction;
